version: 2.1

base_img: &base_img
  docker:
    - image: cimg/base:stable

commands:
  print_pipeline_id:
    description: Print workflow id
    parameters:
      id:
        type: string
    steps:
      - run: echo << parameters.id >>

workflows:
  version: 2
  build:
    jobs:
      - run_print_pipeline_id_command::
          id: << pipeline.id >>

jobs:
  run_print_pipeline_id_command:
    <<: *base_img
    steps:
      - print_pipeline_id
