version: 2.1

base_img: &base_img
  docker:
    - image: cimg/base:stable

command:
  print_pipeline_id:
    description: Print workflow id
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

workflows:
  version: 2
  build:
    jobs:
      - run_print_pipeline_id_command

jobs:
  run_print_pipeline_id_command:
    <<: *base_img
    steps:
      - print_pipeline_id
