version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: mkdir -p /tmp/workspace && touch $_/output.txt
      - run:
          name: Save hello world output to a file
          command: echo "hello world" >> /tmp/workspace/output.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths: [output.txt]

  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Print output file content
          command: cat /tmp/workspace/output.txt
