version: 2.1

jobs:
  failing_job:
    docker:
    - image: cimg/base:stable
    steps:
      - run: return 1
      - run:
          command: echo "Hello Error!"
          when: on_fail

workflows:
  version: 2
  build:
    jobs:
      - failing_job
